"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Al (https://sketchfab.com/lightningocelot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-board-a0d61768bc504082901728ec9603fa0d
Title: Chess Board
*/

import { useGLTF } from "@react-three/drei";
import { Center } from "@react-three/drei";

export function Model({ piece = "king", ...props }) {
  const { nodes, materials } = useGLTF("/scene.gltf");

  const pieces = {
    rook: nodes.Object_3,
    knight: nodes.Object_4,
    bishop: nodes.Object_5,
    queen: nodes.Object_6,
    king: nodes.Object_7,
    pawn: nodes.Object_8,
  };

  const meshData = pieces[piece];

  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      {meshData && (
        <mesh
          castShadow
          receiveShadow
          geometry={meshData.geometry}
          material={materials.glass}
        />
      )}
    </group>
  );
}

useGLTF.preload("/scene.gltf");
