"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wasted (https://sketchfab.com/wastedmerc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-pieces-a06ec9a1bea14787bd4bbcd0749a1726
Title: Chess Pieces
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export function Model({ piece = "king", props }) {
  const { nodes, materials } = useGLTF("/scene.gltf");

  const metalMaterial = new THREE.MeshStandardMaterial({
    roughness: 0.2,
    metalness: 1.0,
    color: "#bbbbbb",
  });

  return (
    <group {...props} dispose={null}>
      {/* Pawn */}
      {piece === "pawn" && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={metalMaterial}
          scale={[1, 0.2, 1]}
        />
      )}
      {/* King */}
      {piece === "king" && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.001"]}
          scale={[1, 0.2, 1]}
        />
      )}
      {/* Queen */}
      {piece === "queen" && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.001"]}
          scale={[1, 0.2, 1]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/scene.gltf");
